### PR TITLE
Fix error message accuracy

### LINKED ISSUE #29: Problem with the message returned when type coverage tests fail
I have a project which I was testing using this library. For return types, if I set the return type coverage level to 66 I get this message:

```
Out of 9930 possible return types, only 6551 - 66.0 % actually have it. Add more return types to get over 66
```

The problem here is that the message seems to imply that my actual coverage is 66.0% but it is actually 6551/9930 = 65.97%. If we are rounding we should round down so that we show a value that, if the user sets in the config, the tests will pass. Otherwise the message just looks weird and leaves you wondering what you did wrong.

Another problem is that if I use the new possibility to use floats and I set the value, for example, to 66.1 I get the same message. The "Add more return types to get over" part should use the float value, not the rounded value

### PR DESCRIPTION
**Pull request by carlos-granados**
Fixes #29

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Thank you :+1:

File: src/Rules/ReturnTypeCoverageRule.php [hunk 1]
```diff
@@ -23,7 +23,7 @@
     /**
      * @var string
      */
-    public const ERROR_MESSAGE = 'Out of %d possible return types, only %d - %.1f %% actually have it. Add more return types to get over %d %%';
+    public const ERROR_MESSAGE = 'Out of %d possible return types, only %d - %.1f %% actually have it. Add more return types to get over %s %%';
```
Comment (staabm) [inline src/Rules/ReturnTypeCoverageRule.php:26]: I wonder why we need this change only for return-types, but not property and param types?

Comment (carlos-granados) [reply src/Rules/ReturnTypeCoverageRule.php:26]: You are right. Let me add a new PR with the change to the other two messages
